# Generated by Django 5.2.16 on 2026-07-18 03:13

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_DEPARTMENTS = [
    'TVL',
    'ABM & Mathematics',
    'Science & Social Sciences',
    'PE & Language',
    'Admin',
]


def seed_and_map_departments(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    User = apps.get_model('accounts', 'User')
    departments = {name: Department.objects.get_or_create(name=name)[0] for name in DEFAULT_DEPARTMENTS}
    aliases = {
        'Mathematics': 'ABM & Mathematics',
        'Science': 'Science & Social Sciences',
        'Office of the Principal': 'Admin',
    }
    for user in User.objects.all():
        if user.role == 'ASSISTANT_PRINCIPAL':
            user.department = departments['Admin']
        elif user.department_legacy:
            target_name = aliases.get(user.department_legacy, user.department_legacy)
            user.department = Department.objects.get_or_create(name=target_name)[0]
        user.save(update_fields=['department'])


def restore_department_text(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.select_related('department'):
        user.department_legacy = user.department.name if user.department else ''
        user.save(update_fields=['department_legacy'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('PASSWORD', 'Email and password'), ('GOOGLE', 'Google'), ('BOTH', 'Email/password and Google')], default='PASSWORD', max_length=12),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='department_legacy',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.department'),
        ),
        migrations.RunPython(seed_and_map_departments, restore_department_text),
        migrations.RemoveField(
            model_name='user',
            name='department_legacy',
        ),
    ]
