# Generated by Django 5.2.16 on 2026-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departments_and_google_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_subject',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
