# Generated by Django 5.2.16 on 2026-07-18 04:23

import django.db.models.deletion
from django.db import migrations, models


ROLE_POSITIONS = {
    "TEACHER": [f"Teacher {level}" for level in ("I", "II", "III", "IV", "V", "VI", "VII")],
    "MASTER_TEACHER": [f"Master Teacher {level}" for level in ("I", "II", "III", "IV", "V")],
    "ASSISTANT_PRINCIPAL": [f"Principal {level}" for level in ("I", "II", "III", "IV", "V")],
}


def seed_and_map_positions(apps, schema_editor):
    Position = apps.get_model("accounts", "Position")
    User = apps.get_model("accounts", "User")
    positions = {}
    for role, names in ROLE_POSITIONS.items():
        for name in names:
            positions[(role, name)] = Position.objects.get_or_create(role=role, name=name)[0]
    for user in User.objects.all():
        if user.is_superuser or not user.position_legacy:
            continue
        name = user.position_legacy
        if user.role == "ASSISTANT_PRINCIPAL":
            if name == "Assistant Principal":
                name = "Principal I"
            else:
                name = name.replace("Assistant Principal", "Principal")
        user.position = positions.get((user.role, name)) or Position.objects.get_or_create(role=user.role, name=name)[0]
        user.save(update_fields=["position"])


def restore_position_text(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.select_related("position"):
        user.position_legacy = user.position.name if user.position else ""
        user.save(update_fields=["position_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clear_superadmin_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('MASTER_TEACHER', 'Master Teacher'), ('ASSISTANT_PRINCIPAL', 'Principal')], default='TEACHER', max_length=24),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('MASTER_TEACHER', 'Master Teacher'), ('ASSISTANT_PRINCIPAL', 'Principal')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('role', 'name'),
                'constraints': [models.UniqueConstraint(fields=('name', 'role'), name='unique_position_per_role')],
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='position_legacy',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.position'),
        ),
        migrations.RunPython(seed_and_map_positions, restore_position_text),
        migrations.RemoveField(
            model_name='user',
            name='position_legacy',
        ),
    ]
