import { useEffect, useState } from 'react'
import { CameraAltOutlined, KeyOutlined, LockOutlined, SecurityOutlined } from '@mui/icons-material'
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, Grid, InputLabel, MenuItem, Select, Stack, Switch, TextField, Typography } from '@mui/material'
import api, { errorMessage } from '../api/client'
import { PageIntro, initials, roleLabel } from '../components/Common'
import { useAuth } from '../context/AuthContext'

function PasswordDialog({ open, onClose }) {
  const [form, setForm] = useState({ current_password: '', new_password: '', confirm: '' })
  const [status, setStatus] = useState({ error: '', success: '' }); const [busy, setBusy] = useState(false)
  const submit = async () => {
    if (form.new_password !== form.confirm) return setStatus({ error: 'New passwords do not match.', success: '' })
    setBusy(true)
    try {
      const { data } = await api.post('/auth/change-password/', form)
      setStatus({ success: data.detail, error: '' }); setForm({ current_password: '', new_password: '', confirm: '' })
    } catch (err) { setStatus({ error: errorMessage(err), success: '' }) } finally { setBusy(false) }
  }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs"><DialogTitle>Change password</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{status.error && <Alert severity="error">{status.error}</Alert>}{status.success && <Alert severity="success">{status.success}</Alert>}<TextField label="Current password" type="password" value={form.current_password} onChange={(event) => setForm({ ...form, current_password: event.target.value })} /><TextField label="New password" type="password" value={form.new_password} onChange={(event) => setForm({ ...form, new_password: event.target.value })} /><TextField label="Confirm new password" type="password" value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Close</Button><Button variant="contained" onClick={submit} disabled={busy || !form.current_password || !form.new_password}>Change password</Button></DialogActions></Dialog>
}

function TwoFactorDialog({ open, onClose, onEnabled }) {
  const [setup, setSetup] = useState(null); const [code, setCode] = useState(''); const [error, setError] = useState('')
  const load = async () => { if (!setup) { try { const { data } = await api.get('/auth/2fa/setup/'); setSetup(data) } catch (err) { setError(errorMessage(err)) } } }
  if (open && !setup && !error) load()
  const verify = async () => { try { await api.post('/auth/2fa/verify/', { code }); onEnabled(); onClose() } catch (err) { setError(errorMessage(err)) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs"><DialogTitle>Set up two-factor authentication</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>Scan this code with an authenticator app, then enter its six-digit code.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{setup && <Stack alignItems="center" spacing={2}><Box component="img" src={setup.qr_code} alt="Authenticator QR code" width={210} height={210} /><Typography variant="caption" color="text.secondary" sx={{ wordBreak: 'break-all' }}>Manual key: {setup.secret}</Typography><TextField label="Verification code" inputProps={{ inputMode: 'numeric', maxLength: 6 }} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} fullWidth /></Stack>}</DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={code.length !== 6} onClick={verify}>Enable 2FA</Button></DialogActions></Dialog>
}

export default function ProfilePage() {
  const { user, setUser, refreshProfile } = useAuth()
  const [form, setForm] = useState({ first_name: user.first_name, last_name: user.last_name, email: user.email, department_id: user.department_id || '', position_id: user.position_id || '', mobile: user.mobile || '', bio: user.bio })
  const [departments, setDepartments] = useState([]); const [positions, setPositions] = useState([]); const [avatar, setAvatar] = useState(null)
  const [status, setStatus] = useState({ error: '', success: '' }); const [passwordOpen, setPasswordOpen] = useState(false); const [twoFactorOpen, setTwoFactorOpen] = useState(false)

  useEffect(() => {
    if (!user.is_superuser) Promise.all([api.get('/auth/departments/'), api.get(`/auth/positions/?role=${user.role}`)]).then(([departmentResponse, positionResponse]) => { setDepartments(departmentResponse.data.results || departmentResponse.data); setPositions(positionResponse.data.results || positionResponse.data) }).catch((err) => setStatus({ error: errorMessage(err), success: '' }))
  }, [user.is_superuser, user.role])
  useEffect(() => { refreshProfile().catch(() => {}) }, [refreshProfile])

  const save = async () => {
    const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value || '')); if (avatar) body.append('avatar', avatar)
    try {
      const { data } = await api.patch('/auth/profile/', body)
      setUser(data); localStorage.setItem('user', JSON.stringify(data)); setStatus({ success: 'Profile updated successfully.', error: '' })
    } catch (err) { setStatus({ error: errorMessage(err), success: '' }) }
  }

  return <><PageIntro eyebrow="Your account" title="Profile & security" subtitle={user.is_superuser ? 'Your protected system identity and sign-in security.' : 'Keep your faculty information and sign-in protections current.'} />{status.error && <Alert severity="error" sx={{ mb: 2 }}>{status.error}</Alert>}{status.success && <Alert severity="success" sx={{ mb: 2 }}>{status.success}</Alert>}
    <Grid container spacing={2.5}><Grid size={{ xs: 12, lg: 8 }}><Card><CardContent>
      <Stack direction={{ xs: 'column', sm: 'row' }} gap={2.5} alignItems={{ sm: 'center' }} mb={3}><Box position="relative"><Avatar src={avatar ? URL.createObjectURL(avatar) : user.avatar_url} sx={{ width: 88, height: 88, bgcolor: 'primary.main', fontSize: 28 }}>{initials(user)}</Avatar>{!user.is_superuser && <Button component="label" variant="contained" size="small" sx={{ position: 'absolute', minWidth: 32, width: 32, height: 32, p: 0, right: -4, bottom: 0, borderRadius: '50%' }}><CameraAltOutlined fontSize="small" /><input hidden type="file" accept="image/*" onChange={(event) => setAvatar(event.target.files[0])} /></Button>}</Box><Box flex={1}><Typography variant="h6" fontWeight={750}>{user.full_name}</Typography><Typography color="text.secondary">{user.is_superuser ? 'SUPERADMIN' : roleLabel(user.role)} · {user.employee_id}</Typography>{user.designations?.length > 0 && <Stack direction="row" gap={0.75} flexWrap="wrap" mt={1}>{user.designations.map((designation) => <Chip key={designation.id} size="small" color={designation.can_create_shared_repositories ? 'primary' : 'default'} variant="outlined" label={designation.name} />)}</Stack>}</Box></Stack>
      {!user.is_superuser && user.can_create_shared_repositories && user.role !== 'ASSISTANT_PRINCIPAL' && <Alert severity="success" sx={{ mb: 2 }}>Your active designation authorizes you to initiate and manage purpose-specific shared repositories.</Alert>}
      {user.is_superuser ? <><Alert severity="info" sx={{ mb: 2 }}>This is a system-managed superadmin identity. Profile details are read-only, and department, position, and About information do not apply.</Alert><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField label="Full name" fullWidth value={user.full_name} slotProps={{ input: { readOnly: true } }} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField label="Username" fullWidth value={user.username} slotProps={{ input: { readOnly: true } }} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField label="Email" fullWidth value={user.email} slotProps={{ input: { readOnly: true } }} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField label="Employee ID" fullWidth value={user.employee_id || 'System account'} slotProps={{ input: { readOnly: true } }} /></Grid></Grid></> : <><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField label="First name" fullWidth value={form.first_name} onChange={(event) => setForm({ ...form, first_name: event.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField label="Last name" fullWidth value={form.last_name} onChange={(event) => setForm({ ...form, last_name: event.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField label="Email" fullWidth value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField label="Mobile" fullWidth value={form.mobile} onChange={(event) => setForm({ ...form, mobile: event.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><FormControl size="small" fullWidth disabled={user.role === 'ASSISTANT_PRINCIPAL'}><InputLabel>Department</InputLabel><Select label="Department" value={form.department_id} onChange={(event) => setForm({ ...form, department_id: event.target.value })}>{departments.map((department) => <MenuItem key={department.id} value={department.id}>{department.name}</MenuItem>)}</Select></FormControl></Grid><Grid size={{ xs: 12, sm: 6 }}><FormControl size="small" fullWidth><InputLabel>Position</InputLabel><Select label="Position" value={form.position_id} onChange={(event) => setForm({ ...form, position_id: event.target.value })}>{positions.map((position) => <MenuItem key={position.id} value={position.id}>{position.name}</MenuItem>)}</Select></FormControl></Grid><Grid size={12}><TextField label="About" multiline minRows={3} fullWidth value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} /></Grid></Grid><Button variant="contained" sx={{ mt: 2.5 }} onClick={save}>Save profile</Button></>}
    </CardContent></Card></Grid><Grid size={{ xs: 12, lg: 4 }}><Stack spacing={2.5}><Card><CardContent><Stack direction="row" gap={1.5} alignItems="center" mb={2}><Box width={42} height={42} borderRadius={2.5} bgcolor="primary.light" color="primary.dark" display="grid" sx={{ placeItems: 'center' }}><LockOutlined /></Box><Box><Typography fontWeight={750}>Password</Typography><Typography variant="caption" color="text.secondary">{user.has_usable_password ? 'Email confirmation included' : 'This account uses Google sign-in'}</Typography></Box></Stack><Button variant="outlined" fullWidth startIcon={<KeyOutlined />} disabled={!user.has_usable_password} onClick={() => setPasswordOpen(true)}>{user.has_usable_password ? 'Change password' : 'Managed by Google'}</Button></CardContent></Card><Card><CardContent><Stack direction="row" gap={1.5} alignItems="center"><Box width={42} height={42} borderRadius={2.5} bgcolor="primary.light" color="primary.dark" display="grid" sx={{ placeItems: 'center' }}><SecurityOutlined /></Box><Box flex={1}><Typography fontWeight={750}>Two-factor authentication</Typography><Typography variant="caption" color="text.secondary">{user.two_factor_enabled ? 'Your account is protected' : 'Add an extra sign-in step'}</Typography></Box><Switch checked={user.two_factor_enabled} onChange={() => !user.two_factor_enabled && setTwoFactorOpen(true)} /></Stack></CardContent></Card></Stack></Grid></Grid>
    <PasswordDialog open={passwordOpen} onClose={() => setPasswordOpen(false)} /><TwoFactorDialog open={twoFactorOpen} onClose={() => setTwoFactorOpen(false)} onEnabled={refreshProfile} />
  </>
}
