import { useState } from 'react'
import { ArrowBackRounded, HowToRegOutlined, SchoolRounded } from '@mui/icons-material'
import { Alert, Box, Button, Card, CardContent, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { Link } from 'react-router-dom'
import api, { errorMessage } from '../api/client'

export default function RegisterPage() {
  const [form, setForm] = useState({ first_name: '', last_name: '', email: '', employee_id: '', department: '', position: '', role: 'TEACHER', password: '', password_confirm: '' })
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const change = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post('/auth/register/', form); setSuccess(data.detail) } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Box minHeight="100vh" bgcolor="background.default" px={2} py={{ xs: 3, md: 6 }}>
    <Stack direction="row" alignItems="center" justifyContent="center" gap={1.2} mb={3}><Box width={42} height={42} bgcolor="primary.main" color="white" borderRadius={2.5} display="grid" sx={{ placeItems: 'center' }}><SchoolRounded /></Box><Box><Typography fontWeight={800}>Faculty eRepository</Typography><Typography variant="caption" color="text.secondary">Faculty account application</Typography></Box></Stack>
    <Card sx={{ maxWidth: 760, mx: 'auto' }}><CardContent sx={{ p: { xs: 3, sm: 5 } }}><Box width={48} height={48} borderRadius={3} bgcolor="primary.light" color="primary.dark" display="grid" sx={{ placeItems: 'center' }} mb={2}><HowToRegOutlined /></Box><Typography variant="h4">Create your account</Typography><Typography color="text.secondary" mt={.75} mb={3}>Submit your school details. The Assistant Principal will review and approve your access.</Typography>
      {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{success ? <><Alert severity="success" sx={{ mb: 3 }}>{success}</Alert><Button component={Link} to="/login" variant="contained" startIcon={<ArrowBackRounded />}>Return to sign in</Button></> : <Box component="form" onSubmit={submit}><Stack spacing={2}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="First name" fullWidth required value={form.first_name} onChange={change('first_name')} /><TextField label="Last name" fullWidth required value={form.last_name} onChange={change('last_name')} /></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="School email" type="email" fullWidth required value={form.email} onChange={change('email')} /><TextField label="Employee ID" fullWidth required value={form.employee_id} onChange={change('employee_id')} /></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="Department" fullWidth required value={form.department} onChange={change('department')} /><TextField label="Position" fullWidth required value={form.position} onChange={change('position')} /></Stack><FormControl size="small" fullWidth><InputLabel>Faculty role</InputLabel><Select label="Faculty role" value={form.role} onChange={change('role')}><MenuItem value="TEACHER">Teacher</MenuItem><MenuItem value="MASTER_TEACHER">Master Teacher</MenuItem></Select></FormControl><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="Password" type="password" fullWidth required helperText="At least 8 characters" value={form.password} onChange={change('password')} /><TextField label="Confirm password" type="password" fullWidth required value={form.password_confirm} onChange={change('password_confirm')} /></Stack><Stack direction={{ xs: 'column-reverse', sm: 'row' }} justifyContent="space-between" gap={1}><Button component={Link} to="/login" startIcon={<ArrowBackRounded />}>Back to sign in</Button><Button type="submit" variant="contained" disabled={busy}>{busy ? 'Submitting…' : 'Submit registration'}</Button></Stack></Stack></Box>}
    </CardContent></Card>
  </Box>
}
