import { useCallback, useEffect, useMemo, useState } from 'react'
import { AddRounded, ArchiveOutlined, CloudUploadOutlined, DeleteOutlineRounded, DownloadRounded, FolderOutlined, FolderSharedOutlined, HistoryRounded, MoreVertRounded, SearchRounded } from '@mui/icons-material'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, IconButton, InputAdornment, InputLabel, Menu, MenuItem, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material'
import api, { errorMessage } from '../api/client'
import { EmptyState, ErrorBlock, FileTypeChip, formatBytes, formatDate, LoadingBlock, PageIntro } from '../components/Common'
import { useAuth } from '../context/AuthContext'

function UploadDialog({ open, onClose, repositories, onSaved }) {
  const [form, setForm] = useState({ repository: '', title: '', description: '', tags: '', revision_notes: '' }); const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (open && repositories.length && !form.repository) setForm((value) => ({ ...value, repository: repositories[0].id })) }, [open, repositories, form.repository])
  const submit = async () => { setBusy(true); setError(''); const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); body.append('file', file); try { await api.post('/documents/', body); setForm({ repository: repositories[0]?.id || '', title: '', description: '', tags: '', revision_notes: '' }); setFile(null); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Upload a document</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<FormControl size="small" fullWidth><InputLabel>Repository</InputLabel><Select label="Repository" value={form.repository} onChange={(e) => setForm({ ...form, repository: e.target.value })}>{repositories.map((repo) => <MenuItem key={repo.id} value={repo.id}>{repo.name} ({repo.kind.toLowerCase()})</MenuItem>)}</Select></FormControl><TextField label="Document title" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><TextField label="Description" multiline minRows={2} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><TextField label="Tags" helperText="Separate tags with commas" value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} /><TextField label="Revision note" placeholder="Initial upload" value={form.revision_notes} onChange={(e) => setForm({ ...form, revision_notes: e.target.value })} /><Button component="label" variant="outlined" startIcon={<CloudUploadOutlined />} sx={{ py: 2, borderStyle: 'dashed' }}>{file ? `${file.name} · ${formatBytes(file.size)}` : 'Choose document (max 50 MB)'}<input hidden type="file" accept=".doc,.docx,.xls,.xlsx,.ppt,.pptx,.pdf,.txt,.csv,.odt,.ods,.odp,.jpg,.jpeg,.png,.zip" onChange={(e) => setFile(e.target.files[0])} /></Button></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={submit} disabled={busy || !file || !form.title || !form.repository}>{busy ? 'Uploading…' : 'Upload'}</Button></DialogActions></Dialog>
}

function SharedRepositoryDialog({ open, onClose, onSaved }) {
  const [form, setForm] = useState({ name: '', description: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async () => { setBusy(true); setError(''); try { await api.post('/repositories/', form); setForm({ name: '', description: '' }); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Create shared repository</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<TextField label="Repository name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><TextField label="Description" multiline minRows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Alert severity="info">With no selected members, this repository is visible to all active faculty.</Alert></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!form.name || busy} onClick={submit}>Create repository</Button></DialogActions></Dialog>
}

function VersionsDialog({ document, open, onClose, onChanged }) {
  const [versions, setVersions] = useState([]); const [file, setFile] = useState(null); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = useCallback(() => { if (document) api.get(`/documents/${document.id}/versions/`).then(({ data }) => setVersions(data)) }, [document])
  useEffect(load, [load, open])
  const upload = async () => { setBusy(true); setError(''); const body = new FormData(); body.append('file', file); body.append('revision_notes', notes); try { await api.post(`/documents/${document.id}/versions/`, body); setFile(null); setNotes(''); load(); onChanged() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  const download = async (version) => { const { data } = await api.get(`/versions/${version.id}/download/`, { responseType: 'blob' }); const url = URL.createObjectURL(data); const link = window.document.createElement('a'); link.href = url; link.download = version.original_filename; link.click(); URL.revokeObjectURL(url) }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>{document?.title} · Revision history</DialogTitle><DialogContent>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack divider={<Divider />} mb={3}>{versions.map((version) => <Stack key={version.id} direction="row" gap={1.5} alignItems="center" py={1.5}><Box width={38} height={38} borderRadius={2} bgcolor="primary.light" color="primary.dark" display="grid" sx={{ placeItems: 'center' }}><Typography fontWeight={800}>v{version.version_number}</Typography></Box><Box flex={1} minWidth={0}><Typography fontWeight={700} noWrap>{version.original_filename}</Typography><Typography variant="caption" color="text.secondary">{formatBytes(version.file_size)} · {version.uploaded_by.full_name} · {formatDate(version.created_at)}</Typography>{version.revision_notes && <Typography variant="body2" color="text.secondary">{version.revision_notes}</Typography>}</Box><Tooltip title="Download"><IconButton onClick={() => download(version)}><DownloadRounded /></IconButton></Tooltip></Stack>)}</Stack><Typography fontWeight={750} mb={1.5}>Upload a new revision</Typography><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5}><Button component="label" variant="outlined" startIcon={<CloudUploadOutlined />} sx={{ minWidth: 190 }}>{file ? file.name : 'Choose new file'}<input hidden type="file" onChange={(e) => setFile(e.target.files[0])} /></Button><TextField label="Revision notes" value={notes} onChange={(e) => setNotes(e.target.value)} fullWidth /><Button variant="contained" onClick={upload} disabled={!file || busy}>Upload</Button></Stack></DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>
}

function DocumentRow({ document, onVersions, onRefresh }) {
  const { user, isAdmin } = useAuth(); const [anchor, setAnchor] = useState(null)
  const canManage = isAdmin || document.owner.id === user.id
  const archive = async () => { setAnchor(null); await api.post(`/documents/${document.id}/archive/`); onRefresh() }
  const remove = async () => { setAnchor(null); if (window.confirm(`Permanently delete “${document.title}” and every revision?`)) { await api.delete(`/documents/${document.id}/`); onRefresh() } }
  return <Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} gap={1.5} py={1.6}><Box width={46} height={46} borderRadius={2.5} bgcolor={document.repository_name ? 'primary.light' : 'grey.100'} color="primary.dark" display="grid" flex="0 0 auto" sx={{ placeItems: 'center' }}><DescriptionIcon filename={document.latest_version?.original_filename} /></Box><Box flex={1} minWidth={0}><Stack direction="row" alignItems="center" gap={1}><Typography fontWeight={750} noWrap>{document.title}</Typography>{document.is_archived && <Chip label="Archived" size="small" />}</Stack><Typography variant="caption" color="text.secondary">{document.repository_name} · {document.owner.full_name} · Updated {formatDate(document.updated_at)}</Typography></Box><Stack direction="row" gap={1} alignItems="center"><FileTypeChip filename={document.latest_version?.original_filename} /><Chip size="small" label={`${document.version_count || 1} revision${document.version_count === 1 ? '' : 's'}`} variant="outlined" /><Tooltip title="Revision history"><IconButton onClick={() => onVersions(document)}><HistoryRounded /></IconButton></Tooltip>{canManage && <><IconButton onClick={(e) => setAnchor(e.currentTarget)}><MoreVertRounded /></IconButton><Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => setAnchor(null)}><MenuItem onClick={archive}><ArchiveOutlined fontSize="small" sx={{ mr: 1.5 }} />{document.is_archived ? 'Restore' : 'Archive'}</MenuItem><MenuItem onClick={remove} sx={{ color: 'error.main' }}><DeleteOutlineRounded fontSize="small" sx={{ mr: 1.5 }} />Delete permanently</MenuItem></Menu></>}</Stack></Stack>
}

function DescriptionIcon({ filename = '' }) { return filename.toLowerCase().endsWith('.pdf') ? <Typography fontWeight={900} fontSize={12}>PDF</Typography> : <FolderOutlined /> }

export default function RepositoriesPage() {
  const { isAdmin } = useAuth(); const [repositories, setRepositories] = useState([]); const [documents, setDocuments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState('all'); const [search, setSearch] = useState(''); const [uploadOpen, setUploadOpen] = useState(false); const [repoOpen, setRepoOpen] = useState(false); const [versionDoc, setVersionDoc] = useState(null)
  const load = useCallback(async () => { setError(''); try { const [repos, docs] = await Promise.all([api.get('/repositories/'), api.get('/documents/?ordering=-updated_at')]); setRepositories(repos.data.results || repos.data); setDocuments(docs.data.results || docs.data) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  const filtered = useMemo(() => documents.filter((doc) => (selected === 'all' || String(doc.repository) === String(selected)) && (!search || `${doc.title} ${doc.description} ${doc.tags} ${doc.owner.full_name}`.toLowerCase().includes(search.toLowerCase()))), [documents, selected, search])
  if (loading) return <LoadingBlock />
  if (error) return <ErrorBlock message={error} retry={load} />
  return <><PageIntro eyebrow="Document workspace" title="Repositories" subtitle="Keep your files organized, traceable, and available to the right people." action={<Stack direction="row" gap={1}>{isAdmin && <Button variant="outlined" startIcon={<FolderSharedOutlined />} onClick={() => setRepoOpen(true)}>New shared repository</Button>}<Button variant="contained" startIcon={<AddRounded />} onClick={() => setUploadOpen(true)}>Upload document</Button></Stack>} />
    <Card><CardContent sx={{ pb: '16px !important' }}><Tabs value={selected} onChange={(_, value) => setSelected(value)} variant="scrollable" scrollButtons="auto" sx={{ mb: 2, borderBottom: '1px solid', borderColor: 'divider' }}><Tab value="all" label={`All files (${documents.length})`} />{repositories.map((repo) => <Tab key={repo.id} value={String(repo.id)} label={`${repo.kind === 'SHARED' ? 'Shared · ' : ''}${repo.name} (${repo.document_count})`} />)}</Tabs><TextField fullWidth placeholder="Search by title, tag, description, or owner…" value={search} onChange={(e) => setSearch(e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRounded /></InputAdornment> }} sx={{ mb: 1 }} />{filtered.length ? <Stack divider={<Divider />}>{filtered.map((doc) => <DocumentRow key={doc.id} document={doc} onVersions={setVersionDoc} onRefresh={load} />)}</Stack> : <EmptyState title="No documents found" text={search ? 'Try a different search.' : 'Upload the first file to this repository.'} action={!search && <Button variant="contained" onClick={() => setUploadOpen(true)}>Upload document</Button>} />}</CardContent></Card>
    <UploadDialog open={uploadOpen} onClose={() => setUploadOpen(false)} repositories={repositories} onSaved={load} /><SharedRepositoryDialog open={repoOpen} onClose={() => setRepoOpen(false)} onSaved={load} /><VersionsDialog document={versionDoc} open={Boolean(versionDoc)} onClose={() => setVersionDoc(null)} onChanged={load} />
  </>
}
