import { useCallback, useEffect, useMemo, useState } from 'react'
import { AddRounded, ArchiveOutlined, CloudUploadOutlined, CreateNewFolderRounded, DeleteOutlineRounded, DownloadRounded, EditOutlined, FolderOpenRounded, FolderOutlined, FolderSharedOutlined, HistoryRounded, MoreVertRounded, SearchRounded } from '@mui/icons-material'
import { Alert, Autocomplete, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, FormControlLabel, IconButton, InputAdornment, InputLabel, Menu, MenuItem, Radio, RadioGroup, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material'
import api, { errorMessage } from '../api/client'
import { EmptyState, ErrorBlock, FileTypeChip, formatBytes, formatDate, LoadingBlock, PageIntro } from '../components/Common'
import { useAuth } from '../context/AuthContext'

function UploadDialog({ open, onClose, repositories, folders, initialRepository, initialFolder, onSaved }) {
  const [form, setForm] = useState({ repository: '', folder: '', title: '', description: '', tags: '', revision_notes: '' }); const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => {
    if (!open) return
    const repository = initialRepository || repositories[0]?.id || ''
    const folder = initialFolder && folders.some((item) => item.id === initialFolder && item.repository === repository) ? initialFolder : ''
    setForm({ repository, folder, title: '', description: '', tags: '', revision_notes: '' }); setFile(null); setError('')
  }, [open, initialRepository, initialFolder, repositories, folders])
  const availableFolders = folders.filter((folder) => String(folder.repository) === String(form.repository))
  const submit = async () => { setBusy(true); setError(''); const body = new FormData(); Object.entries(form).forEach(([key, value]) => { if (key !== 'folder' || value) body.append(key, value) }); body.append('file', file); try { await api.post('/documents/', body); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Upload a document</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<Stack direction={{ xs: 'column', sm: 'row' }} gap={2}><FormControl size="small" fullWidth><InputLabel>Repository</InputLabel><Select label="Repository" value={form.repository} onChange={(e) => setForm({ ...form, repository: e.target.value, folder: '' })}>{repositories.map((repo) => <MenuItem key={repo.id} value={repo.id}>{repo.name} ({repo.kind.toLowerCase()})</MenuItem>)}</Select></FormControl><FormControl size="small" fullWidth><InputLabel>Folder</InputLabel><Select label="Folder" value={form.folder} onChange={(e) => setForm({ ...form, folder: e.target.value })}><MenuItem value=""><em>Root folder</em></MenuItem>{availableFolders.map((folder) => <MenuItem key={folder.id} value={folder.id}>{folder.name}</MenuItem>)}</Select></FormControl></Stack><Alert severity="info">The document will be saved in {form.folder ? availableFolders.find((folder) => folder.id === form.folder)?.name : 'the root folder'}.</Alert><TextField label="Document title" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><TextField label="Description" multiline minRows={2} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><TextField label="Tags" helperText="Separate tags with commas" value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} /><TextField label="Revision note" placeholder="Initial upload" value={form.revision_notes} onChange={(e) => setForm({ ...form, revision_notes: e.target.value })} /><Button component="label" variant="outlined" startIcon={<CloudUploadOutlined />} sx={{ py: 2, borderStyle: 'dashed' }}>{file ? `${file.name} · ${formatBytes(file.size)}` : 'Choose document (max 50 MB)'}<input hidden type="file" accept=".doc,.docx,.xls,.xlsx,.ppt,.pptx,.pdf,.txt,.csv,.odt,.ods,.odp,.jpg,.jpeg,.png,.zip" onChange={(e) => setFile(e.target.files[0])} /></Button></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={submit} disabled={busy || !file || !form.title.trim() || !form.repository}>{busy ? 'Uploading…' : 'Upload'}</Button></DialogActions></Dialog>
}

function FolderDialog({ folder, repository, open, onClose, onSaved }) {
  const [name, setName] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { setName(folder?.name || ''); setError('') }, [folder, open])
  const submit = async () => { setBusy(true); setError(''); try { if (folder) await api.patch(`/folders/${folder.id}/`, { name: name.trim() }); else await api.post('/folders/', { name: name.trim(), repository: repository.id }); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs"><DialogTitle>{folder ? 'Rename folder' : 'Create folder'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<Alert severity="info">Repository: <strong>{repository?.name}</strong></Alert><TextField label="Folder name" autoFocus required value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && name.trim() && !busy) submit() }} helperText={folder ? 'The folder ownership will remain unchanged.' : 'You will be recorded as the folder owner.'} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!name.trim() || busy} onClick={submit}>{busy ? 'Saving…' : folder ? 'Save name' : 'Create folder'}</Button></DialogActions></Dialog>
}

function FolderTile({ label, count, owner, selected, canManage, onSelect, onEdit, onDelete }) {
  return <Box minWidth={190} maxWidth={240} border="1px solid" borderColor={selected ? 'primary.main' : 'divider'} bgcolor={selected ? 'primary.light' : 'background.paper'} borderRadius={2.5} p={1.5} sx={{ cursor: 'pointer', transition: 'all .15s ease', '&:hover': { borderColor: 'primary.main', transform: 'translateY(-1px)' } }} onClick={onSelect}><Stack direction="row" alignItems="center" gap={1}><Box width={36} height={36} borderRadius={2} bgcolor={selected ? 'white' : 'grey.100'} color="primary.main" display="grid" sx={{ placeItems: 'center' }}><FolderOpenRounded fontSize="small" /></Box><Box flex={1} minWidth={0}><Typography variant="body2" fontWeight={750} noWrap>{label}</Typography><Typography variant="caption" color="text.secondary" noWrap display="block">{count} document{count === 1 ? '' : 's'}{owner ? ` · ${owner}` : ''}</Typography></Box>{canManage && <Stack direction="row"><Tooltip title="Rename folder"><IconButton size="small" onClick={(event) => { event.stopPropagation(); onEdit() }}><EditOutlined sx={{ fontSize: 17 }} /></IconButton></Tooltip><Tooltip title="Remove folder"><IconButton size="small" color="error" onClick={(event) => { event.stopPropagation(); onDelete() }}><DeleteOutlineRounded sx={{ fontSize: 17 }} /></IconButton></Tooltip></Stack>}</Stack></Box>
}

function SharedRepositoryDialog({ repository, faculty, open, onClose, onSaved }) {
  const [form, setForm] = useState({ name: '', description: '', audience: 'all', member_ids: [] }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => {
    const memberIds = repository?.member_ids || []
    setForm({ name: repository?.name || '', description: repository?.description || '', audience: memberIds.length ? 'selected' : 'all', member_ids: memberIds })
    setError('')
  }, [repository, open])
  const selectedMembers = faculty.filter((member) => form.member_ids.includes(member.id))
  const submit = async () => {
    setBusy(true); setError('')
    const payload = { name: form.name.trim(), description: form.description, member_ids: form.audience === 'all' ? [] : form.member_ids }
    try { if (repository) await api.patch(`/repositories/${repository.id}/`, payload); else await api.post('/repositories/', payload); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) }
  }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{repository ? 'Edit shared repository' : 'Create shared repository'}</DialogTitle><DialogContent><Stack spacing={2.25} pt={1}>{error && <Alert severity="error">{error}</Alert>}<TextField label="Repository name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><TextField label="Description" multiline minRows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><FormControl><Typography fontWeight={700} mb={0.5}>Who can view this repository?</Typography><RadioGroup value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })}><FormControlLabel value="all" control={<Radio />} label="All active faculty" /><FormControlLabel value="selected" control={<Radio />} label="Selected faculty members" /></RadioGroup></FormControl>{form.audience === 'selected' && <Autocomplete multiple options={faculty} value={selectedMembers} isOptionEqualToValue={(option, value) => option.id === value.id} getOptionLabel={(option) => option.full_name} onChange={(_, members) => setForm({ ...form, member_ids: members.map((member) => member.id) })} renderInput={(params) => <TextField {...params} label="Faculty members" placeholder="Search by name" helperText="Only selected faculty members will have access." />} renderOption={(props, option) => <li {...props} key={option.id}><Stack><Typography variant="body2" fontWeight={650}>{option.full_name}</Typography><Typography variant="caption" color="text.secondary">{option.position || option.role_label} · {option.department || 'No department'}</Typography></Stack></li>} />}<Alert severity="info">{form.audience === 'all' ? 'Every active Teacher and Master Teacher can view this repository.' : `${form.member_ids.length} faculty member${form.member_ids.length === 1 ? '' : 's'} selected.`}</Alert></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!form.name.trim() || busy || (form.audience === 'selected' && !form.member_ids.length)} onClick={submit}>{busy ? 'Saving…' : repository ? 'Save changes' : 'Create repository'}</Button></DialogActions></Dialog>
}

function VersionsDialog({ document, open, onClose, onChanged }) {
  const { user, isSuperadmin, canManageRepositories } = useAuth()
  const [versions, setVersions] = useState([]); const [file, setFile] = useState(null); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const canUploadRevision = !isSuperadmin && (canManageRepositories || document?.owner?.id === user?.id)
  const load = useCallback(() => { if (document) api.get(`/documents/${document.id}/versions/`).then(({ data }) => setVersions(data)) }, [document])
  useEffect(load, [load, open])
  const upload = async () => { setBusy(true); setError(''); const body = new FormData(); body.append('file', file); body.append('revision_notes', notes); try { await api.post(`/documents/${document.id}/versions/`, body); setFile(null); setNotes(''); load(); onChanged() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  const download = async (version) => { const { data } = await api.get(`/versions/${version.id}/download/`, { responseType: 'blob' }); const url = URL.createObjectURL(data); const link = window.document.createElement('a'); link.href = url; link.download = version.original_filename; link.click(); URL.revokeObjectURL(url) }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>{document?.title} · Revision history</DialogTitle><DialogContent>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack divider={<Divider />} mb={canUploadRevision ? 3 : 0}>{versions.map((version) => <Stack key={version.id} direction="row" gap={1.5} alignItems="center" py={1.5}><Box width={38} height={38} borderRadius={2} bgcolor="primary.light" color="primary.dark" display="grid" sx={{ placeItems: 'center' }}><Typography fontWeight={800}>v{version.version_number}</Typography></Box><Box flex={1} minWidth={0}><Typography fontWeight={700} noWrap>{version.original_filename}</Typography><Typography variant="caption" color="text.secondary">{formatBytes(version.file_size)} · {version.uploaded_by.full_name} · {formatDate(version.created_at)}</Typography>{version.revision_notes && <Typography variant="body2" color="text.secondary">{version.revision_notes}</Typography>}</Box><Tooltip title="Download"><IconButton onClick={() => download(version)}><DownloadRounded /></IconButton></Tooltip></Stack>)}</Stack>{canUploadRevision && <><Typography fontWeight={750} mb={1.5}>Upload a new revision</Typography><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5}><Button component="label" variant="outlined" startIcon={<CloudUploadOutlined />} sx={{ minWidth: 190 }}>{file ? file.name : 'Choose new file'}<input hidden type="file" onChange={(e) => setFile(e.target.files[0])} /></Button><TextField label="Revision notes" value={notes} onChange={(e) => setNotes(e.target.value)} fullWidth /><Button variant="contained" onClick={upload} disabled={!file || busy}>Upload</Button></Stack></>}</DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>
}

function DocumentRow({ document, onVersions, onRefresh }) {
  const { user, isSuperadmin, canManageRepositories } = useAuth(); const [anchor, setAnchor] = useState(null)
  const canManage = !isSuperadmin && (canManageRepositories || document.owner.id === user.id)
  const archive = async () => { setAnchor(null); await api.post(`/documents/${document.id}/archive/`); onRefresh() }
  const remove = async () => { setAnchor(null); if (window.confirm(`Permanently delete “${document.title}” and every revision?`)) { await api.delete(`/documents/${document.id}/`); onRefresh() } }
  return <Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} gap={1.5} py={1.6}><Box width={46} height={46} borderRadius={2.5} bgcolor={document.repository_name ? 'primary.light' : 'grey.100'} color="primary.dark" display="grid" flex="0 0 auto" sx={{ placeItems: 'center' }}><DescriptionIcon filename={document.latest_version?.original_filename} /></Box><Box flex={1} minWidth={0}><Stack direction="row" alignItems="center" gap={1}><Typography fontWeight={750} noWrap>{document.title}</Typography>{document.is_archived && <Chip label="Archived" size="small" />}</Stack><Typography variant="caption" color="text.secondary">{document.repository_name} · {document.folder_name || 'Root folder'} · {document.owner.full_name} · Updated {formatDate(document.updated_at)}</Typography></Box><Stack direction="row" gap={1} alignItems="center"><FileTypeChip filename={document.latest_version?.original_filename} /><Chip size="small" label={`${document.version_count || 1} revision${document.version_count === 1 ? '' : 's'}`} variant="outlined" /><Tooltip title="Revision history"><IconButton onClick={() => onVersions(document)}><HistoryRounded /></IconButton></Tooltip>{canManage && <><IconButton onClick={(e) => setAnchor(e.currentTarget)}><MoreVertRounded /></IconButton><Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => setAnchor(null)}><MenuItem onClick={archive}><ArchiveOutlined fontSize="small" sx={{ mr: 1.5 }} />{document.is_archived ? 'Restore' : 'Archive'}</MenuItem><MenuItem onClick={remove} sx={{ color: 'error.main' }}><DeleteOutlineRounded fontSize="small" sx={{ mr: 1.5 }} />Delete permanently</MenuItem></Menu></>}</Stack></Stack>
}

function DescriptionIcon({ filename = '' }) { return filename.toLowerCase().endsWith('.pdf') ? <Typography fontWeight={900} fontSize={12}>PDF</Typography> : <FolderOutlined /> }

export default function RepositoriesPage() {
  const { user, canManageRepositories, isSuperadmin } = useAuth()
  const [repositories, setRepositories] = useState([]); const [documents, setDocuments] = useState([]); const [folders, setFolders] = useState([]); const [faculty, setFaculty] = useState([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState('all'); const [folderFilter, setFolderFilter] = useState('all'); const [search, setSearch] = useState('')
  const [uploadOpen, setUploadOpen] = useState(false); const [repoOpen, setRepoOpen] = useState(false); const [repoEditing, setRepoEditing] = useState(null); const [folderOpen, setFolderOpen] = useState(false); const [folderEditing, setFolderEditing] = useState(null); const [versionDoc, setVersionDoc] = useState(null)
  const canUploadDocuments = !isSuperadmin
  const load = useCallback(async () => {
    setError('')
    try {
      const [repos, docs, folderResponse, members] = await Promise.all([
        api.get('/repositories/'),
        api.get('/documents/?ordering=-updated_at'),
        api.get('/folders/'),
        canManageRepositories ? api.get('/repositories/eligible-members/') : Promise.resolve({ data: [] }),
      ])
      setRepositories(repos.data.results || repos.data); setDocuments(docs.data.results || docs.data); setFolders(folderResponse.data.results || folderResponse.data); setFaculty(members.data.results || members.data)
    } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) }
  }, [canManageRepositories])
  useEffect(() => { load() }, [load])
  const selectedRepository = repositories.find((repository) => String(repository.id) === String(selected))
  const repositoryFolders = folders.filter((folder) => String(folder.repository) === String(selected))
  const rootDocumentCount = Math.max((selectedRepository?.document_count || 0) - repositoryFolders.reduce((total, folder) => total + folder.document_count, 0), 0)
  const filtered = useMemo(() => documents.filter((doc) => {
    if (selected !== 'all' && String(doc.repository) !== String(selected)) return false
    if (selected !== 'all' && folderFilter === 'root' && doc.folder) return false
    if (selected !== 'all' && !['all', 'root'].includes(folderFilter) && String(doc.folder) !== String(folderFilter)) return false
    return !search || `${doc.title} ${doc.description} ${doc.tags} ${doc.owner.full_name} ${doc.folder_name || 'root'}`.toLowerCase().includes(search.toLowerCase())
  }), [documents, selected, folderFilter, search])
  const canCreateFolder = Boolean(selectedRepository && !isSuperadmin && (selectedRepository.kind === 'SHARED' || selectedRepository.owner.id === user.id))
  const canManageFolder = (folder) => !isSuperadmin && (folder.owner?.id === user.id || (canManageRepositories && selectedRepository?.kind === 'SHARED'))
  const removeFolder = async (folder) => {
    if (!window.confirm(`Remove “${folder.name}”? Its ${folder.document_count} document${folder.document_count === 1 ? '' : 's'} will be moved to the root folder.`)) return
    try { await api.delete(`/folders/${folder.id}/`); if (String(folderFilter) === String(folder.id)) setFolderFilter('all'); load() } catch (err) { setError(errorMessage(err)) }
  }
  if (loading) return <LoadingBlock />
  if (error) return <ErrorBlock message={error} retry={load} />
  return <><PageIntro eyebrow="Document workspace" title="Repositories" subtitle={canManageRepositories ? 'Keep files organized, traceable, and available to the right people.' : 'Browse the repositories and documents available to you.'} action={(canManageRepositories || canUploadDocuments) && <Stack direction="row" gap={1}>{canManageRepositories && <Button variant="outlined" startIcon={<FolderSharedOutlined />} onClick={() => { setRepoEditing(null); setRepoOpen(true) }}>New shared repository</Button>}{canUploadDocuments && <Button variant="contained" startIcon={<AddRounded />} onClick={() => setUploadOpen(true)}>Upload document</Button>}</Stack>} />
    <Card><CardContent sx={{ pb: '16px !important' }}>
      <Tabs value={selected} onChange={(_, value) => { setSelected(value); setFolderFilter('all') }} variant="scrollable" scrollButtons="auto" sx={{ mb: 2, borderBottom: '1px solid', borderColor: 'divider' }}><Tab value="all" label={`All files (${documents.length})`} />{repositories.map((repo) => <Tab key={repo.id} value={String(repo.id)} label={`${repo.kind === 'SHARED' ? 'Shared · ' : ''}${repo.name} (${repo.document_count})`} />)}</Tabs>
      {selectedRepository?.kind === 'SHARED' && <Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} gap={1.5} bgcolor="grey.50" borderRadius={2.5} p={2} mb={2}><Box flex={1}><Stack direction="row" gap={1} alignItems="center"><Typography fontWeight={750}>{selectedRepository.name}</Typography><Chip size="small" label={selectedRepository.member_ids.length ? `${selectedRepository.member_ids.length} selected member${selectedRepository.member_ids.length === 1 ? '' : 's'}` : 'All active faculty'} color={selectedRepository.member_ids.length ? 'secondary' : 'primary'} variant="outlined" /></Stack><Typography variant="body2" color="text.secondary">{selectedRepository.description || 'No description provided.'}</Typography></Box>{canManageRepositories && <Button startIcon={<EditOutlined />} onClick={() => { setRepoEditing(selectedRepository); setRepoOpen(true) }}>Edit repository</Button>}</Stack>}
      {selectedRepository && <Box mb={2.5}><Stack direction="row" alignItems="center" justifyContent="space-between" mb={1.25}><Box><Typography fontWeight={750}>Folders</Typography><Typography variant="caption" color="text.secondary">Choose a folder to filter this repository. Folder ownership is shown for shared content.</Typography></Box>{canCreateFolder && <Button size="small" startIcon={<CreateNewFolderRounded />} onClick={() => { setFolderEditing(null); setFolderOpen(true) }}>New folder</Button>}</Stack><Stack direction="row" gap={1.25} overflow="auto" pb={1}><FolderTile label="All folders" count={selectedRepository.document_count} selected={folderFilter === 'all'} onSelect={() => setFolderFilter('all')} /><FolderTile label="Root folder" count={rootDocumentCount} selected={folderFilter === 'root'} onSelect={() => setFolderFilter('root')} />{repositoryFolders.map((folder) => <FolderTile key={folder.id} label={folder.name} count={folder.document_count} owner={selectedRepository.kind === 'SHARED' ? `Owner: ${folder.owner?.full_name || 'Former faculty'}` : ''} selected={String(folderFilter) === String(folder.id)} canManage={canManageFolder(folder)} onSelect={() => setFolderFilter(String(folder.id))} onEdit={() => { setFolderEditing(folder); setFolderOpen(true) }} onDelete={() => removeFolder(folder)} />)}</Stack></Box>}
      <TextField fullWidth placeholder="Search by title, folder, tag, description, or owner…" value={search} onChange={(e) => setSearch(e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRounded /></InputAdornment> }} sx={{ mb: 1 }} />
      {filtered.length ? <Stack divider={<Divider />}>{filtered.map((doc) => <DocumentRow key={doc.id} document={doc} onVersions={setVersionDoc} onRefresh={load} />)}</Stack> : <EmptyState title="No documents found" text={search ? 'Try a different search.' : canUploadDocuments ? 'Upload the first file to this location.' : 'No documents are available in this location.'} action={!search && canUploadDocuments && <Button variant="contained" onClick={() => setUploadOpen(true)}>Upload document</Button>} />}
    </CardContent></Card>
    <UploadDialog open={uploadOpen} onClose={() => setUploadOpen(false)} repositories={repositories} folders={folders} initialRepository={selectedRepository?.id} initialFolder={!['all', 'root'].includes(folderFilter) ? Number(folderFilter) : null} onSaved={load} />
    <FolderDialog folder={folderEditing} repository={selectedRepository} open={folderOpen} onClose={() => setFolderOpen(false)} onSaved={load} />
    <SharedRepositoryDialog repository={repoEditing} faculty={faculty} open={repoOpen} onClose={() => setRepoOpen(false)} onSaved={load} />
    <VersionsDialog document={versionDoc} open={Boolean(versionDoc)} onClose={() => setVersionDoc(null)} onChanged={load} />
  </>
}
