import { useCallback, useEffect, useMemo, useState } from 'react'
import { AddRounded, CheckCircleOutlineRounded, EditOutlined, SearchRounded } from '@mui/icons-material'
import { Alert, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, IconButton, InputAdornment, InputLabel, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material'
import api, { errorMessage } from '../api/client'
import { EmptyState, ErrorBlock, LoadingBlock, PageIntro, UserAvatar } from '../components/Common'

const blankUser = { first_name: '', last_name: '', email: '', username: '', employee_id: '', department: '', position: '', role: 'TEACHER', password: '', is_active: true }

function UserDialog({ user, open, onClose, onSaved }) {
  const [form, setForm] = useState(blankUser); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { setForm(user ? { ...blankUser, ...user, password: '' } : blankUser); setError('') }, [user, open])
  const change = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  const submit = async () => { setBusy(true); setError(''); const payload = { ...form }; if (!payload.password) delete payload.password; try { if (user) await api.patch(`/auth/users/${user.id}/`, payload); else await api.post('/auth/users/', payload); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{user ? 'Edit faculty account' : 'Add faculty account'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<Stack direction="row" spacing={2}><TextField label="First name" fullWidth required value={form.first_name} onChange={change('first_name')} /><TextField label="Last name" fullWidth required value={form.last_name} onChange={change('last_name')} /></Stack><TextField label="Email" type="email" required value={form.email} onChange={change('email')} /><TextField label="Username" required value={form.username} onChange={change('username')} /><Stack direction="row" spacing={2}><TextField label="Employee ID" fullWidth value={form.employee_id || ''} onChange={change('employee_id')} /><FormControl size="small" fullWidth><InputLabel>Role</InputLabel><Select label="Role" value={form.role} onChange={change('role')}><MenuItem value="TEACHER">Teacher</MenuItem><MenuItem value="MASTER_TEACHER">Master Teacher</MenuItem><MenuItem value="ASSISTANT_PRINCIPAL">Assistant Principal</MenuItem></Select></FormControl></Stack><Stack direction="row" spacing={2}><TextField label="Department" fullWidth value={form.department} onChange={change('department')} /><TextField label="Position" fullWidth value={form.position} onChange={change('position')} /></Stack><TextField label={user ? 'New password (optional)' : 'Temporary password (optional)'} type="password" value={form.password} onChange={change('password')} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={submit} disabled={busy || !form.email || !form.username}>{busy ? 'Saving…' : 'Save account'}</Button></DialogActions></Dialog>
}

export default function StaffPage() {
  const [users, setUsers] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState(undefined); const [dialogOpen, setDialogOpen] = useState(false)
  const load = useCallback(() => api.get('/auth/users/').then(({ data }) => setUsers(data.results || data)).catch((err) => setError(errorMessage(err))).finally(() => setLoading(false)), [])
  useEffect(() => { load() }, [load]); const shown = useMemo(() => users.filter((u) => `${u.full_name} ${u.email} ${u.employee_id} ${u.department}`.toLowerCase().includes(search.toLowerCase())), [users, search])
  const approve = async (user) => { await api.post(`/auth/users/${user.id}/approve/`); load() }
  if (loading) return <LoadingBlock />; if (error) return <ErrorBlock message={error} retry={load} />
  return <><PageIntro eyebrow="Administration" title="Staff management" subtitle="Review registrations and manage faculty access and roles." action={<Button variant="contained" startIcon={<AddRounded />} onClick={() => { setEditing(null); setDialogOpen(true) }}>Add faculty</Button>} /><Card><CardContent><TextField fullWidth placeholder="Search faculty…" value={search} onChange={(e) => setSearch(e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRounded /></InputAdornment> }} sx={{ mb: 2 }} />{shown.length ? <Stack divider={<Divider />}>{shown.map((user) => <Stack key={user.id} direction={{ xs: 'column', sm: 'row' }} gap={1.5} alignItems={{ sm: 'center' }} py={1.6}><UserAvatar user={user} size={44} /><Stack flex={1} minWidth={0}><Stack direction="row" gap={1} alignItems="center"><Typography fontWeight={750}>{user.full_name}</Typography>{!user.is_active && <Chip label="Awaiting approval" size="small" color="warning" />}</Stack><Typography variant="body2" color="text.secondary">{user.email} · {user.employee_id || 'No employee ID'}</Typography></Stack><Stack alignItems={{ sm: 'end' }}><Chip size="small" label={user.role.replaceAll('_', ' ')} sx={{ fontWeight: 650 }} /><Typography variant="caption" color="text.secondary">{user.department || 'No department'}</Typography></Stack>{!user.is_active && <Tooltip title="Approve account"><IconButton color="success" onClick={() => approve(user)}><CheckCircleOutlineRounded /></IconButton></Tooltip>}<Tooltip title="Edit account"><IconButton onClick={() => { setEditing(user); setDialogOpen(true) }}><EditOutlined /></IconButton></Tooltip></Stack>)}</Stack> : <EmptyState title="No faculty found" text="Try a different search or add a faculty account." />}</CardContent></Card><UserDialog user={editing} open={dialogOpen} onClose={() => setDialogOpen(false)} onSaved={load} /></>
}
