import { useCallback, useEffect, useMemo, useState } from 'react'
import { AddRounded, CheckCircleOutlineRounded, DeleteOutlineRounded, EditOutlined, SearchRounded } from '@mui/icons-material'
import { Alert, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, FormControlLabel, IconButton, InputAdornment, InputLabel, MenuItem, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material'
import api, { errorMessage } from '../api/client'
import { EmptyState, ErrorBlock, LoadingBlock, PageIntro, roleLabel, UserAvatar } from '../components/Common'
import { useAuth } from '../context/AuthContext'

const blankUser = { first_name: '', last_name: '', email: '', username: '', employee_id: '', department_id: '', position_id: '', role: 'TEACHER', password: '', is_active: true, is_superuser: false }

async function fetchAll(url) {
  const items = []
  let next = url
  while (next) {
    const response = await api.get(next)
    if (Array.isArray(response.data)) return response.data
    items.push(...response.data.results)
    next = response.data.next
  }
  return items
}

function UserDialog({ user, open, onClose, onSaved, departments, positions, isSuperadmin }) {
  const [form, setForm] = useState(blankUser); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { setForm(user ? { ...blankUser, ...user, password: '' } : blankUser); setError('') }, [user, open])
  const change = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  const submit = async () => {
    setBusy(true); setError(''); const payload = { ...form }; if (!payload.password) delete payload.password
    try { if (user) await api.patch(`/auth/users/${user.id}/`, payload); else await api.post('/auth/users/', payload); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) }
  }
  const principal = form.role === 'ASSISTANT_PRINCIPAL'
  const availablePositions = positions.filter((position) => position.role === form.role && position.is_active)
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{user ? 'Edit faculty account' : 'Add faculty account'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="First name" fullWidth required value={form.first_name} onChange={change('first_name')} /><TextField label="Last name" fullWidth required value={form.last_name} onChange={change('last_name')} /></Stack><TextField label="Email" type="email" required value={form.email} onChange={change('email')} /><TextField label="Username" required value={form.username} onChange={change('username')} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label="Employee ID" fullWidth value={form.employee_id || ''} onChange={change('employee_id')} /><FormControl size="small" fullWidth><InputLabel>Role</InputLabel><Select label="Role" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value, position_id: '' })}><MenuItem value="TEACHER">Teacher</MenuItem><MenuItem value="MASTER_TEACHER">Master Teacher</MenuItem>{isSuperadmin && <MenuItem value="ASSISTANT_PRINCIPAL">Principal</MenuItem>}</Select></FormControl></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><FormControl size="small" fullWidth disabled={principal}><InputLabel>Department</InputLabel><Select label="Department" value={principal ? departments.find((item) => item.name === 'Admin')?.id || '' : form.department_id} onChange={change('department_id')}>{departments.filter((item) => item.is_active).map((department) => <MenuItem key={department.id} value={department.id}>{department.name}</MenuItem>)}</Select></FormControl><FormControl size="small" fullWidth><InputLabel>Position</InputLabel><Select label="Position" value={form.position_id} onChange={change('position_id')}>{availablePositions.map((position) => <MenuItem key={position.id} value={position.id}>{position.name}</MenuItem>)}</Select></FormControl></Stack>{isSuperadmin && <FormControlLabel control={<Checkbox checked={form.is_superuser} onChange={(event) => setForm({ ...form, is_superuser: event.target.checked })} />} label="Grant superadmin access" />}<TextField label={user ? 'New password (optional)' : 'Temporary password (optional)'} type="password" value={form.password} onChange={change('password')} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={submit} disabled={busy || !form.email || !form.username || (!form.is_superuser && !form.position_id)}>{busy ? 'Saving…' : 'Save account'}</Button></DialogActions></Dialog>
}

function DepartmentDialog({ department, open, onClose, onSaved }) {
  const [name, setName] = useState(''); const [isActive, setIsActive] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { setName(department?.name || ''); setIsActive(department?.is_active ?? true); setError('') }, [department, open])
  const submit = async () => { setBusy(true); setError(''); try { if (department) await api.patch(`/auth/departments/${department.id}/`, { name, is_active: isActive }); else await api.post('/auth/departments/', { name, is_active: isActive }); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs"><DialogTitle>{department ? 'Edit department' : 'Add department'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<TextField label="Department name" autoFocus required value={name} onChange={(event) => setName(event.target.value)} /><FormControlLabel control={<Checkbox checked={isActive} onChange={(event) => setIsActive(event.target.checked)} />} label="Available for faculty assignment" /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!name.trim() || busy} onClick={submit}>Save department</Button></DialogActions></Dialog>
}

function PositionDialog({ position, open, onClose, onSaved }) {
  const [form, setForm] = useState({ name: '', role: 'TEACHER', is_active: true }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { setForm(position ? { name: position.name, role: position.role, is_active: position.is_active } : { name: '', role: 'TEACHER', is_active: true }); setError('') }, [position, open])
  const submit = async () => { setBusy(true); setError(''); try { if (position) await api.patch(`/auth/positions/${position.id}/`, form); else await api.post('/auth/positions/', form); onSaved(); onClose() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs"><DialogTitle>{position ? 'Edit position' : 'Add position'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error && <Alert severity="error">{error}</Alert>}<FormControl size="small"><InputLabel>Role</InputLabel><Select label="Role" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><MenuItem value="TEACHER">Teacher</MenuItem><MenuItem value="MASTER_TEACHER">Master Teacher</MenuItem><MenuItem value="ASSISTANT_PRINCIPAL">Principal</MenuItem></Select></FormControl><TextField label="Position name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><FormControlLabel control={<Checkbox checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} />} label="Available for faculty assignment" /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!form.name.trim() || busy} onClick={submit}>Save position</Button></DialogActions></Dialog>
}

export default function StaffPage() {
  const { user: currentUser, isSuperadmin } = useAuth()
  const [users, setUsers] = useState([]); const [departments, setDepartments] = useState([]); const [positions, setPositions] = useState([])
  const [search, setSearch] = useState(''); const [tab, setTab] = useState('faculty'); const [roleGroup, setRoleGroup] = useState('TEACHER'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [editing, setEditing] = useState(undefined); const [dialogOpen, setDialogOpen] = useState(false)
  const [departmentEditing, setDepartmentEditing] = useState(undefined); const [departmentOpen, setDepartmentOpen] = useState(false)
  const [positionEditing, setPositionEditing] = useState(undefined); const [positionOpen, setPositionOpen] = useState(false)

  const load = useCallback(async () => {
    setError('')
    try {
      const [allUsers, allDepartments, allPositions] = await Promise.all([fetchAll('/auth/users/'), fetchAll('/auth/departments/'), fetchAll('/auth/positions/')])
      setUsers(allUsers); setDepartments(allDepartments); setPositions(allPositions)
    } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) }
  }, [])
  useEffect(() => { load() }, [load])
  const roleCounts = useMemo(() => users.reduce((counts, staff) => ({ ...counts, [staff.role]: (counts[staff.role] || 0) + 1 }), {}), [users])
  const shown = useMemo(() => users.filter((staff) => staff.role === roleGroup && `${staff.full_name} ${staff.email} ${staff.employee_id} ${staff.department} ${staff.position}`.toLowerCase().includes(search.toLowerCase())), [users, roleGroup, search])
  const canManage = (staff) => isSuperadmin || (staff.id !== currentUser.id && staff.role !== 'ASSISTANT_PRINCIPAL' && !staff.is_superuser)
  const approve = async (staff) => { await api.post(`/auth/users/${staff.id}/approve/`); load() }
  const removeDepartment = async (department) => { if (window.confirm(`Delete “${department.name}”?`)) { try { await api.delete(`/auth/departments/${department.id}/`); load() } catch (err) { setError(errorMessage(err)) } } }
  const removePosition = async (position) => { if (window.confirm(`Delete “${position.name}”?`)) { try { await api.delete(`/auth/positions/${position.id}/`); load() } catch (err) { setError(errorMessage(err)) } } }
  const newAction = tab === 'faculty' ? () => { setEditing(null); setDialogOpen(true) } : tab === 'departments' ? () => { setDepartmentEditing(null); setDepartmentOpen(true) } : () => { setPositionEditing(null); setPositionOpen(true) }
  const actionLabel = tab === 'faculty' ? 'Add faculty' : tab === 'departments' ? 'Add department' : 'Add position'
  if (loading) return <LoadingBlock />; if (error) return <ErrorBlock message={error} retry={load} />

  return <><PageIntro eyebrow="Administration" title="Staff management" subtitle={isSuperadmin ? 'Manage faculty access, Principals, departments, and role-based positions.' : 'Review registrations and manage faculty access. Principal access requires a superadmin.'} action={<Button variant="contained" startIcon={<AddRounded />} onClick={newAction}>{actionLabel}</Button>} />{isSuperadmin && <Tabs value={tab} onChange={(_, value) => setTab(value)} sx={{ mb: 2 }}><Tab value="faculty" label="Faculty accounts" /><Tab value="departments" label="Departments" /><Tab value="positions" label="Positions" /></Tabs>}
    {tab === 'faculty' && <Card><CardContent><TextField fullWidth placeholder={`Search ${roleGroup === 'TEACHER' ? 'teachers' : roleGroup === 'MASTER_TEACHER' ? 'master teachers' : 'principals'}…`} value={search} onChange={(event) => setSearch(event.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><SearchRounded /></InputAdornment> }} sx={{ mb: 1 }} /><Tabs value={roleGroup} onChange={(_, value) => { setRoleGroup(value); setSearch('') }} variant="scrollable" scrollButtons="auto" sx={{ mb: 2, borderBottom: '1px solid', borderColor: 'divider' }}><Tab value="TEACHER" label={`Teachers (${roleCounts.TEACHER || 0})`} /><Tab value="MASTER_TEACHER" label={`Master Teachers (${roleCounts.MASTER_TEACHER || 0})`} />{isSuperadmin && <Tab value="ASSISTANT_PRINCIPAL" label={`Principals (${roleCounts.ASSISTANT_PRINCIPAL || 0})`} />}</Tabs>{shown.length ? <Stack divider={<Divider />}>{shown.map((staff) => <Stack key={staff.id} direction={{ xs: 'column', sm: 'row' }} gap={1.5} alignItems={{ sm: 'center' }} py={1.6}><UserAvatar user={staff} size={44} /><Stack flex={1} minWidth={0}><Stack direction="row" gap={1} alignItems="center"><Typography fontWeight={750}>{staff.full_name}</Typography>{!staff.is_active && <Chip label="Awaiting approval" size="small" color="warning" />}{staff.is_superuser && <Chip label="Superadmin" size="small" color="secondary" />}</Stack><Typography variant="body2" color="text.secondary">{staff.email} · {staff.employee_id || 'No employee ID'}</Typography></Stack><Stack alignItems={{ sm: 'end' }}><Chip size="small" label={staff.is_superuser ? 'SUPERADMIN' : roleLabel(staff.role)} sx={{ fontWeight: 650 }} /><Typography variant="caption" color="text.secondary">{staff.position || 'No position'} · {staff.department || 'No department'}</Typography></Stack>{!staff.is_active && canManage(staff) && <Tooltip title="Approve account"><IconButton color="success" onClick={() => approve(staff)}><CheckCircleOutlineRounded /></IconButton></Tooltip>}{canManage(staff) ? <Tooltip title="Edit account"><IconButton onClick={() => { setEditing(staff); setDialogOpen(true) }}><EditOutlined /></IconButton></Tooltip> : <Tooltip title="Only a superadmin can edit this account"><span><IconButton disabled><EditOutlined /></IconButton></span></Tooltip>}</Stack>)}</Stack> : <EmptyState title={`No ${roleGroup === 'TEACHER' ? 'teachers' : roleGroup === 'MASTER_TEACHER' ? 'master teachers' : 'Principals'} found`} text={search ? 'Try a different search.' : 'No faculty accounts are currently assigned to this group.'} />}</CardContent></Card>}
    {tab === 'departments' && <Card><CardContent>{departments.length ? <Stack divider={<Divider />}>{departments.map((department) => <Stack key={department.id} direction="row" gap={1.5} alignItems="center" py={1.6}><Stack flex={1}><Typography fontWeight={750}>{department.name}</Typography><Typography variant="caption" color="text.secondary">{department.user_count} assigned staff · {department.is_active ? 'Active' : 'Inactive'}</Typography></Stack><Chip size="small" color={department.is_active ? 'success' : 'default'} label={department.is_active ? 'Active' : 'Inactive'} /><Tooltip title="Edit department"><IconButton onClick={() => { setDepartmentEditing(department); setDepartmentOpen(true) }}><EditOutlined /></IconButton></Tooltip><Tooltip title={department.name === 'Admin' ? 'Admin cannot be deleted' : 'Delete department'}><span><IconButton color="error" disabled={department.name === 'Admin'} onClick={() => removeDepartment(department)}><DeleteOutlineRounded /></IconButton></span></Tooltip></Stack>)}</Stack> : <EmptyState title="No departments" text="Add the first department." />}</CardContent></Card>}
    {tab === 'positions' && <Card><CardContent>{positions.length ? <Stack divider={<Divider />}>{positions.map((position) => <Stack key={position.id} direction="row" gap={1.5} alignItems="center" py={1.6}><Stack flex={1}><Typography fontWeight={750}>{position.name}</Typography><Typography variant="caption" color="text.secondary">{position.role_label} · {position.user_count} assigned staff</Typography></Stack><Chip size="small" color={position.is_active ? 'success' : 'default'} label={position.is_active ? 'Active' : 'Inactive'} /><Tooltip title="Edit position"><IconButton onClick={() => { setPositionEditing(position); setPositionOpen(true) }}><EditOutlined /></IconButton></Tooltip><Tooltip title="Delete position"><span><IconButton color="error" disabled={position.user_count > 0} onClick={() => removePosition(position)}><DeleteOutlineRounded /></IconButton></span></Tooltip></Stack>)}</Stack> : <EmptyState title="No positions" text="Add the first role-based position." />}</CardContent></Card>}
    <UserDialog user={editing} open={dialogOpen} onClose={() => setDialogOpen(false)} onSaved={load} departments={departments} positions={positions} isSuperadmin={isSuperadmin} />
    <DepartmentDialog department={departmentEditing} open={departmentOpen} onClose={() => setDepartmentOpen(false)} onSaved={load} />
    <PositionDialog position={positionEditing} open={positionOpen} onClose={() => setPositionOpen(false)} onSaved={load} />
  </>
}
